import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { buildGridExportSections } from './gridExportModel.js';

const PDF_FOOTER = 'Generated by JSON Studio';
const PDF_MARGIN_X = 14;
const PDF_CONTENT_TOP = 16;
const PDF_CONTENT_BOTTOM = 18;
const PDF_CELL_PADDING = 3.4;
const PDF_NESTED_GUTTER = PDF_CELL_PADDING * 2;
const PDF_CHAR_WIDTH = 2.3;
const PDF_MIN_KEY_WIDTH = 18;
const PDF_MIN_VALUE_WIDTH = 24;
/** @type {[number, number, number]} */
const PDF_TEXT_COLOR = [35, 42, 58];
/** @type {[number, number, number]} */
const PDF_MUTED_TEXT_COLOR = [108, 113, 150];
/** @type {[number, number, number]} */
const PDF_BORDER_COLOR = [216, 220, 232];
/** @type {[number, number, number]} */
const PDF_KEY_FILL_COLOR = [247, 249, 252];
/** @type {[number, number, number]} */
const PDF_ROW_FILL_COLOR = [255, 255, 255];
/** @type {[number, number, number]} */
const PDF_ALTERNATE_ROW_FILL_COLOR = [252, 253, 255];
/** @type {[number, number, number]} */
const PDF_PARENT_ROW_FILL_COLOR = [246, 248, 251];

/**
 * @typedef {{
 *   keyWidth: number;
 *   valueWidth: number;
 *   totalWidth: number;
 *   children: Record<string, GridPdfLayout>;
 * }} GridPdfLayout
 */

/** @param {string} value */
function estimatePdfTextWidth(value) {
  return Math.max(0, String(value).length * PDF_CHAR_WIDTH);
}

/**
 * @param {import('./gridExportModel.js').GridExportSection} section
 * @param {number} maxWidth
 * @returns {GridPdfLayout}
 */
function buildPdfLayout(section, maxWidth) {
  /** @type {Record<string, GridPdfLayout>} */
  const childLayouts = {};
  const keyWidth = Math.max(
    PDF_MIN_KEY_WIDTH,
    ...section.rows.map((row) => estimatePdfTextWidth(row.key) + PDF_NESTED_GUTTER),
  );

  const valueTextWidth = Math.max(
    PDF_MIN_VALUE_WIDTH,
    ...section.rows.map((row) => estimatePdfTextWidth(row.value) + PDF_NESTED_GUTTER),
  );
  const childLimit = Math.max(PDF_MIN_VALUE_WIDTH, maxWidth - keyWidth - PDF_NESTED_GUTTER);

  let childWidth = 0;
  for (const row of section.rows) {
    if (!row.child) continue;
    const layout = buildPdfLayout(row.child, childLimit);
    childLayouts[row.key] = layout;
    childWidth = Math.max(childWidth, layout.totalWidth + PDF_NESTED_GUTTER);
  }

  const valueWidth = Math.min(
    Math.max(PDF_MIN_VALUE_WIDTH, valueTextWidth, childWidth),
    Math.max(PDF_MIN_VALUE_WIDTH, maxWidth - keyWidth),
  );

  return {
    keyWidth,
    valueWidth,
    totalWidth: keyWidth + valueWidth,
    children: childLayouts,
  };
}

/**
 * @param {unknown} value
 * @param {number} maxWidth
 */
export function getGridPdfLayout(value, maxWidth) {
  return buildPdfLayout(buildGridExportSections(value), maxWidth);
}

/**
 * @param {import('./gridExportModel.js').GridExportSection} section
 * @param {GridPdfLayout} layout
 */
function measurePdfSectionHeight(section, layout) {
  const doc = new jsPDF();
  autoTable(doc, {
    body: section.rows.map((row) => [row.key, row.value]),
    columns: [
      { header: '', dataKey: 'key' },
      { header: '', dataKey: 'value' },
    ],
    showHead: 'never',
    theme: 'grid',
    rowPageBreak: 'avoid',
    startY: 0,
    margin: { left: 0 },
    tableWidth: layout.totalWidth,
    styles: getPdfTableStyles(),
    alternateRowStyles: getPdfAlternateRowStyles(),
    columnStyles: {
      0: getPdfKeyColumnStyle(layout.keyWidth),
      1: { cellWidth: layout.valueWidth },
    },
    didParseCell: (data) => {
      const row = section.rows[data.row.index];
      const childLayout = row?.child ? layout.children[row.key] : null;
      stylePdfCellForRow(data, row);
      if (data.column.index !== 1 || !row?.child || !childLayout) return;
      data.cell.styles.minCellHeight = measurePdfSectionHeight(row.child, childLayout) + PDF_NESTED_GUTTER;
    },
    didDrawPage: () => {},
  });

  const table = /** @type {jsPDF & { lastAutoTable?: { body?: { height: number }[] } }} */ (doc).lastAutoTable;
  return table?.body?.reduce((height, row) => height + row.height, 0) ?? 0;
}

/**
 * @param {unknown} value
 * @param {string} key
 * @param {number} maxWidth
 */
export function getGridPdfSectionHeight(value, key, maxWidth) {
  const section = buildGridExportSections(value);
  const layout = buildPdfLayout(section, maxWidth);
  const row = section.rows.find((entry) => entry.key === key);
  const childLayout = row?.child ? layout.children[key] : null;
  if (!row?.child || !childLayout) return 0;
  return measurePdfSectionHeight(row.child, childLayout);
}

function getPdfTableStyles() {
  return /** @type {Partial<import('jspdf-autotable').Styles>} */ ({
    font: 'helvetica',
    fontSize: 9.5,
    cellPadding: PDF_CELL_PADDING,
    overflow: 'linebreak',
    lineColor: PDF_BORDER_COLOR,
    lineWidth: 0.18,
    textColor: PDF_TEXT_COLOR,
    fillColor: PDF_ROW_FILL_COLOR,
    valign: 'middle',
  });
}

function getPdfAlternateRowStyles() {
  return /** @type {Partial<import('jspdf-autotable').Styles>} */ ({
    fillColor: PDF_ALTERNATE_ROW_FILL_COLOR,
  });
}

/** @param {number} cellWidth */
function getPdfKeyColumnStyle(cellWidth) {
  return /** @type {Partial<import('jspdf-autotable').Styles>} */ ({
    cellWidth,
    fillColor: PDF_KEY_FILL_COLOR,
    fontStyle: 'bold',
    textColor: PDF_TEXT_COLOR,
  });
}

/**
 * @param {import('jspdf-autotable').CellHookData} data
 * @param {import('./gridExportModel.js').GridExportSectionRow | undefined} row
 */
function stylePdfCellForRow(data, row) {
  if (!row?.child) return;

  data.cell.styles.fillColor = PDF_PARENT_ROW_FILL_COLOR;
  data.cell.styles.fontStyle = 'bold';
  if (data.column.index === 1) {
    data.cell.styles.textColor = PDF_MUTED_TEXT_COLOR;
  }
}

/**
 * @param {jsPDF} doc
 */
function decoratePdfPages(doc) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);

    doc.setDrawColor(...PDF_BORDER_COLOR);
    doc.setLineWidth(0.2);
    doc.line(PDF_MARGIN_X, pageHeight - 14, pageWidth - PDF_MARGIN_X, pageHeight - 14);

    doc.setFontSize(8);
    doc.setTextColor(...PDF_MUTED_TEXT_COLOR);
    doc.text(PDF_FOOTER, PDF_MARGIN_X, pageHeight - 8);
    doc.text(`Page ${page} / ${pageCount}`, pageWidth - PDF_MARGIN_X, pageHeight - 8, {
      align: 'right',
    });
  }
}

/**
 * @param {jsPDF} doc
 * @param {import('./gridExportModel.js').GridExportSection} section
 * @param {GridPdfLayout} layout
 * @param {number} startY
 * @param {number} left
 * @returns {number}
 */
function renderPdfSection(doc, section, layout, startY, left) {
  autoTable(doc, {
    body: section.rows.map((row) => [row.key, row.value]),
    columns: [
      { header: '', dataKey: 'key' },
      { header: '', dataKey: 'value' },
    ],
    showHead: 'never',
    theme: 'grid',
    rowPageBreak: 'avoid',
    startY,
    margin: {
      left,
      top: PDF_CONTENT_TOP,
      bottom: PDF_CONTENT_BOTTOM,
    },
    tableWidth: layout.totalWidth,
    styles: getPdfTableStyles(),
    alternateRowStyles: getPdfAlternateRowStyles(),
    columnStyles: {
      0: getPdfKeyColumnStyle(layout.keyWidth),
      1: { cellWidth: layout.valueWidth },
    },
    didParseCell: (data) => {
      const row = section.rows[data.row.index];
      const childLayout = row?.child ? layout.children[row.key] : null;
      stylePdfCellForRow(data, row);
      if (data.column.index !== 1 || !row?.child || !childLayout) return;
      data.cell.styles.minCellHeight = measurePdfSectionHeight(row.child, childLayout) + PDF_NESTED_GUTTER;
    },
    didDrawCell: (data) => {
      const row = section.rows[data.row.index];
      const childLayout = row?.child ? layout.children[row.key] : null;
      if (data.column.index !== 1 || !row?.child || !childLayout) return;
      renderPdfSection(
        doc,
        row.child,
        childLayout,
        data.cell.y + PDF_CELL_PADDING,
        data.cell.x + PDF_CELL_PADDING,
      );
    },
  });
  return /** @type {jsPDF & { lastAutoTable?: { finalY?: number } }} */ (doc).lastAutoTable?.finalY ?? startY;
}

/**
 * @param {import('./gridExportModel.js').GridExportSection} section
 * @returns {number}
 */
function getSheetSectionHeight(section) {
  return section.rows.reduce(
    (height, row) => height + (row.child ? getSheetSectionHeight(row.child) : 1),
    0,
  );
}

/**
 * @param {string[][]} rows
 * @param {number} rowIndex
 * @param {number} columnIndex
 * @param {string} value
 */
function setSheetCell(rows, rowIndex, columnIndex, value) {
  rows[rowIndex] ??= [];
  rows[rowIndex][columnIndex] = value;
}

/**
 * @param {import('./gridExportModel.js').GridExportSection} section
 * @param {string[][]} rows
 * @param {import('xlsx').Range[]} merges
 * @param {number} startRow
 * @param {number} startColumn
 * @returns {number}
 */
function writeSheetSection(section, rows, merges, startRow = 0, startColumn = 0) {
  let rowIndex = startRow;

  for (const row of section.rows) {
    setSheetCell(rows, rowIndex, startColumn, row.key);

    if (!row.child) {
      setSheetCell(rows, rowIndex, startColumn + 1, row.value);
      rowIndex += 1;
      continue;
    }

    const childHeight = getSheetSectionHeight(row.child);
    if (childHeight > 1) {
      merges.push({
        s: { r: rowIndex, c: startColumn },
        e: { r: rowIndex + childHeight - 1, c: startColumn },
      });
    }
    writeSheetSection(row.child, rows, merges, rowIndex, startColumn + 1);
    rowIndex += childHeight;
  }

  return rowIndex - startRow;
}

/** @param {string[][]} rows */
export function getGridSheetColumnWidths(rows) {
  /** @type {number[]} */
  const widths = [];
  for (const row of rows) {
    row.forEach((value, index) => {
      widths[index] = Math.max(widths[index] ?? 0, String(value).length);
    });
  }
  return widths;
}

/** @param {unknown} value */
export function createGridPdfBytes(value) {
  const doc = new jsPDF();
  doc.setProperties({
    creator: 'JSON Studio',
  });
  const pageWidth = doc.internal.pageSize.getWidth();
  const section = buildGridExportSections(value);
  const layout = buildPdfLayout(section, pageWidth - PDF_MARGIN_X * 2);
  renderPdfSection(doc, section, layout, PDF_CONTENT_TOP, PDF_MARGIN_X);
  decoratePdfPages(doc);
  return new Uint8Array(doc.output('arraybuffer'));
}

/** @param {unknown} value */
export function createGridXlsxBytes(value) {
  /** @type {string[][]} */
  const rows = [];
  /** @type {import('xlsx').Range[]} */
  const merges = [];
  writeSheetSection(buildGridExportSections(value), rows, merges);
  const worksheet = XLSX.utils.aoa_to_sheet(rows);
  worksheet['!cols'] = getGridSheetColumnWidths(rows).map((width) => ({ wch: width + 2 }));
  worksheet['!merges'] = merges;

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Grid');
  return new Uint8Array(XLSX.write(workbook, { type: 'array', bookType: 'xlsx' }));
}
